language: python

python:
  - 2.6
  - 2.7

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=drfdiary.settings
  - export PYTHONPATH=$HOME/builds/nairobley/drf-diary
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==2.1 --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE drfdiary_dev;" -U postgres

script:
  - python manage.py test
