language: python

python:
  - 3.5

addons:
  postgresql: "9.4"

services: postgresql

before_install:
  - export PYTHONPATH=$HOME/builds/nairobley/drf-diary
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE drfdiary_test;" -U postgres

script:
  - python drfdiary/manage.py makemigrations api --settings=settings.testing
  - python drfdiary/manage.py migrate --settings=settings.testing
  - coverage run --source=drfdiary drfdiary/manage.py test --settings=settings.testing drfdiary/api --noinput

# run coveralls after successful tests
after_success:
  - coveralls
